version: '3.4'

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: templatesecurity
      POSTGRES_USER: jeanfernades
      POSTGRES_PASSWORD: admin
    volumes:
      - "/var/lib/postgresql/data/"
    container_name: pg_security